### ISSUE TITLE
To record only given programmes with titles or regex

### ISSUE THREAD

**Issue by Konstantinusz** [krizzdewizz/node-icy-rip#1]
Would be nice, to record only given programmes as programme title metadata changes. Till then the ripper would be in listening state. Programmes to record should be declared by title or regex, maybe in a json file. Or maybe to exclude only given programmes and record the rest.

**Comment by krizzdewizz** [comment]
hi Konstantinusz, 
thanks for the suggestion and trying out icy-rip! I think this would be a valuable addition and I will look into it as you proposed.

**Comment by krizzdewizz** [comment]
As with the new version, one can provide a settings file to configure a track filter. Please see the module's documentation. Thanks for trying out.
