### ISSUE TITLE
icy-rip not runnig on raspberry pi

### ISSUE THREAD

**Issue by ovsleep** [krizzdewizz/node-icy-rip#2]
I'm trying to run this on my raspberry PI zero. 
I installed with:
`sudo npm install -g icy-rip` without any issue.
But when I try to run it with:
`icy-rip http://radio2.oceanofm.com:8010`
I get:
`: No such file or directory`
Also tried adding the output directory or even running with sudo, with same luck

**Comment by krizzdewizz** [comment]
Hi, are there any more infos like a stacktrace, line numbers? May it could not find icy-rip itself. What does 'which icy-rip' report?

**Comment by ovsleep** [comment]
No, nothing else.
If I run `which icy-rip` this is the return:
`/usr/local/bin/icy-rip`
Could it be that it's not finding node? or something like that?

**Comment by krizzdewizz** [comment]
hmm, sorry. I can't reproduce. Maybe it needs single/double quotes around the url? Like `icy-rip "http://radio2.oceanofm.com:8010"`

**Comment by ovsleep** [comment]
I finally resolved by changing the `index` file first line to this
`#!/usr/locla/bin/node` 
Seems my $PATH or something is messed up with node.

Thanks for the help
